<a href="https://colab.research.google.com/github/lovelessbhartal12/Convolution-neural-network-CNN-codebase/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)

2.8.0+cu126


In [4]:
if torch.cuda.is_available():
    print("CUDA is available")
else:
    print("CUDA is not available")

CUDA is available


In [5]:
torch.empty(2,3)

tensor([[4.0973e-11, 1.7470e-04, 2.9574e-18],
        [1.7516e-43, 0.0000e+00, 0.0000e+00]])

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.rand(2,3)

tensor([[0.8783, 0.3528, 0.5047],
        [0.9780, 0.9280, 0.4083]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
x=torch.tensor([[1,2,3],[3,4,4]])


In [10]:
x.shape

torch.Size([2, 3])

In [11]:
torch.empty_like(x)

tensor([[         919223554, 288230376151711744,          819905832],
        [         536870912,          919360512,          919360368]])

In [12]:
x.dtype

torch.int64

In [16]:
m=torch.rand(2,3)
n=torch.rand(2,3)


In [15]:
m.add_(n)

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])

In [17]:
m

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [19]:
l=torch.rand(2,3)
w=l
w

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [21]:
x=torch.tensor(3.0,requires_grad=True)
y=x**2



In [22]:
x

tensor(3., requires_grad=True)

In [23]:
y

tensor(9., grad_fn=<PowBackward0>)

In [24]:
y.backward()

In [27]:
x.grad

tensor(6.)

In [29]:
x=torch.tensor(4.0,requires_grad=True)

In [30]:
y=x**2

In [31]:
z=torch.sin(y)

In [32]:
x

tensor(4., requires_grad=True)

In [33]:
y

tensor(16., grad_fn=<PowBackward0>)

In [34]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [35]:
z.backward()

In [37]:
z.grad

/tmp/ipython-input-4110045842.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  z.grad
